# Use ./ to specify the current project root directory
spring.datasource.url=jdbc:h2:file:./timetable_demo_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Optional: Keep the console enabled to view the data
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=none

#flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/demo